# Generated by Django 3.2 on 2021-04-30 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0002_auto_20210430_1106'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='type',
            options={'ordering': ['type']},
        ),
    ]
