# Generated by Django 3.2 on 2021-04-30 09:26

import characters.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0003_alter_type_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='country_origin',
            field=models.TextField(blank=True, verbose_name='Country of origin'),
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('file', models.FileField(null=True, upload_to=characters.models.attachment_path, verbose_name='File')),
                ('type', models.CharField(blank=True, choices=[('audio', 'Audio'), ('image', 'Image'), ('text', 'Text'), ('video', 'Video'), ('other', 'Other')], default='image', help_text='Select allowed attachment type', max_length=5, verbose_name='Attachment type')),
                ('characters', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characters.agent')),
            ],
            options={
                'ordering': ['type'],
            },
        ),
    ]
