# Generated by Django 3.2 on 2021-04-30 09:33

import characters.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0004_auto_20210430_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to=characters.models.poster_path, verbose_name='Poster'),
        ),
    ]
